services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage/app/public:/var/www/storage/app/public
    networks:
      - laravel
    expose:
      - "9000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9001:9001"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: backendtest # nama database
      POSTGRES_USER: haris # username postgres
      POSTGRES_PASSWORD: haris # password postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

  phpmyadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # email login pgadmin
      PGADMIN_DEFAULT_PASSWORD: admin # password login pgadmin
    ports:
      - "9002:80"
    depends_on:
      - db
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
